spring:
  datasource:
    # another client jdbc
    # jdbc:h2:/Users/lhysin/Development/spring-data-rest/persistence/db1;AUTO_SERVER=TRUE;MODE=MariaDB
    url: jdbc:h2:./persistence/db1;AUTO_SERVER=TRUE;MODE=MariaDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /v1/api
logging:
  level:
    h2: debug